name: Lint n Test
on: [pull_request]

permissions:
  contents: read

jobs:
  list-years:
    runs-on: ubuntu-latest
    outputs:
      year: ${{ steps.set-matrix.outputs.year }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "::set-output name=year::$(ls -d 20*/ | jq -R -s -c 'split("\n")[:-1]')"

  test-format-lint:
    name: Test Format Lint
    runs-on: ubuntu-latest
    needs: list-years
    strategy:
      matrix:
        year: ${{ fromJson(needs.list-years.outputs.year) }}
    defaults:
      run:
        working-directory: ./${{ matrix.year }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Format
        id: cargo-fmt
        run: cargo fmt -- --check
      - name: Clippy
        id: cargo-clippy
        run: cargo clippy --all --tests --all-features --no-deps

